spring:
  application:
    name: service-shop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: niit1234
    url: jdbc:mysql://localhost:3306/meituan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
